#!/bin/bash
echo "🚀 Quick Start: CodeGuard AI"
echo "============================="
echo ""
echo "1. First, run the full deployment:"
echo "   ./deploy.sh"
echo ""
echo "2. Or for development:"
echo "   source .venv/bin/activate"
echo "   python scripts/collect_data.py --sample-only"
echo "   python training/train_model.py"
echo "   cd dashboard && python app.py"
echo ""
echo "3. Open browser to: http://localhost:5000"
echo ""
echo "4. Try these example commit messages:"
echo "   - 'Fix memory leak in data parser'"
echo "   - 'Add new API endpoint for users'"
echo "   - 'Update documentation'"
echo "   - 'Fix segmentation fault in array access'"
echo ""
echo "📚 Need help? Check README.md for detailed instructions."
